name: flu2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.20.2
  flutter_speed_dial: ^7.0.0
  mobile_scanner: ^7.1.2
  image_picker: ^1.0.4
  file_picker: ^10.3.3
  shared_preferences: ^2.2.2
  lottie: ^3.3.2
  flutter_image: 4.1.13
  google_mlkit_text_recognition: ^0.15.0
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.3.2
  flutter_staggered_grid_view: ^0.7.0
  rive: ^0.13.20
  tflite_flutter: ^0.12.1
  crypto: ^3.0.3
  flutter_staggered_animations: ^1.1.1
  image_cropper: ^11.0.0
  flutter_image_compress: ^2.1.0
  pdf: ^3.10.8
  printing: ^5.11.1
  image: ^4.5.4
  camera: ^0.11.2
  material_design_icons_flutter: ^7.0.7296
  cupertino_icons: ^1.0.8
  qr_code_tools: ^0.2.0
  google_mlkit_barcode_scanning: ^0.14.1
  open_filex: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: CascadiaCode
      fonts:
        - asset: assets/fonts/CascadiaCode-VariableFont_wght.ttf
        - asset: assets/fonts/CascadiaCode-Italic-VariableFont_wght.ttf
    - family: Parkinsonianos
      fonts:
        - asset: assets/fonts/Parkinsonianos-Regular.ttf
        - asset: assets/fonts/Parkinsonianos-Bold.ttf
          weight: 700
        - asset: assets/fonts/Parkinsonianos-Italic.ttf
          style: italic
